export const galleryCopy = {
  documentTitle: "Gallery | Lumina — Lista 1",
  entry: "Gallery",
  loading: "Caricamento gallery…",
  title: "LUMINA IN FOTO.",
  subtitle: "Le foto della nostra settimana di propaganda.",
  photo: "Foto",
  of: "di",
  openPhoto: "Apri foto",
  back: "Torna a Lumina",
  empty: "Le foto della nostra settimana stanno arrivando.",
  close: "Chiudi la foto",
  previous: "Foto precedente",
  next: "Foto successiva",
  pause: "Pausa",
  resume: "Riprendi",
  hint: "Scorri le foto. Tocca quella al centro per aprirla.",
  error: "La foto non è disponibile. Puoi passare alla successiva.",
};
