import { Component, lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react'
import { Link, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowDown, ArrowUpRight, ArrowUp, Plus, X, ArrowLeft, Sun, Moon } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { usePageMotion } from '@/hooks/usePageMotion'
import { LightReveal } from '@/components/LightReveal'
import { CandidateSection } from '@/components/CandidateSection'
import { Countdown } from '@/components/Countdown'
import { ProgramSection } from '@/components/ProgramSection'
import { GadgetGallery } from '@/components/GadgetGallery'
import { IdeaForm } from '@/components/IdeaForm'
const LuminaScene=lazy(()=>import('@/components/LuminaScene'))
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<img className="scene-fallback" src="/logo.svg" alt=""/>:this.props.children}}
function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><a href="#inizio" className="header-brand" aria-label="Lumina, torna all’inizio"><img src="/favicon.svg" alt=""/><span>LUMINA<span>LISTA 01</span></span></a><div className="header-actions"><a href="#programma">IL PROGRAMMA <ArrowDown size={13}/></a><button className="menu-toggle" aria-expanded={open} aria-controls="main-nav" aria-label={open?'Chiudi menu':'Apri menu'} onClick={()=>setOpen(!open)}>{open?<X size={23}/>:<Plus size={23}/>}</button></div><AnimatePresence>{open&&<motion.nav id="main-nav" className="menu-panel" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);(document.querySelector('.menu-toggle') as HTMLButtonElement)?.focus()}}} aria-label="Navigazione principale">{[['I candidati','candidati'],['Il programma','programma'],['Lumina IRL','irl'],['La tua idea','idea']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={22}/></a>)}</motion.nav>}</AnimatePresence></header>}
function Hero(){const [lit,setLit]=useState(true);return <section id="inizio" className={`hero ${lit?'':'dimmed'}`} aria-labelledby="hero-title"><div className="hero-location hero-enter"><span>LICEO GENTILESCHI</span><span>NAPOLI, ITALIA</span></div><div className="hero-art"><div className="light-orbit"/><div className="hero-beam"/><SceneBoundary><Suspense fallback={<div className="scene-loading"><img src="/favicon.svg" alt=""/></div>}><LuminaScene/></Suspense></SceneBoundary><button className="light-control" onClick={()=>setLit(!lit)} aria-pressed={lit} aria-label={lit?'Abbassa la luce del logo':'Accendi la luce del logo'}>{lit?<Sun size={15}/>:<Moon size={15}/>}<span>{lit?'LA LUCE È NELLE TUE MANI':'TOCCA. FAI LUCE.'}</span></button><span className="hero-art-caption" aria-hidden="true">DAL BUIO, UNA POSSIBILITÀ.</span></div><div className="hero-wordmark hero-enter"><h1 id="hero-title"><img src="/wordmark.svg" alt="Lumina" width="1016" height="305"/></h1><div className="hero-list"><span>LA TUA VOCE. LA NOSTRA LUCE.</span><span>LISTA <b>01</b></span></div></div><div className="hero-bottom hero-enter"><p>Il futuro della nostra scuola<br/>inizia da un’idea. <strong>La tua.</strong></p><a className="discover" href="#intro" aria-label="Scopri Lumina"><ArrowDown size={22}/></a></div><div className="hero-bottomline"><span>SCORRI PER ACCENDERE IL CAMBIAMENTO</span><span>↓</span></div></section>}
function Footer(){return <footer className="footer section-pad"><div className="footer-top"><a href="#inizio" className="footer-brand">LUMINA<span>LISTA 01</span></a><a href="#inizio" className="back-top" aria-label="Torna all’inizio"><ArrowUp size={21}/></a></div><p>Liceo Gentileschi<br/>Napoli, Italia</p><div className="footer-links"><span>CANALI SOCIAL IN ARRIVO</span><Link to="/privacy">PRIVACY <ArrowUpRight size={12}/></Link></div><div className="footer-number" aria-hidden="true">01<span>IL FUTURO<br/>SI ACCENDE.</span></div><div className="footer-bottom"><span>© 2026 LUMINA</span><span>ANTEPRIMA · CONTENUTI PROVVISORI</span></div></footer>}
function Landing(){const root=useRef<HTMLElement>(null);usePageMotion(root);return <><aside className="desktop-rail rail-left" aria-hidden="true"><img className="rail-symbol" src="/favicon.svg" width="30" height="30" alt=""/><span>LUMINA — LISTA 01</span><span className="rail-bottom">UNA NUOVA<br/>PROSPETTIVA.</span></aside><aside className="desktop-rail rail-right" aria-hidden="true"><span>NAPOLI / GENTILESCHI</span><span className="rail-vertical">FROM DARKNESS TO LIGHT</span><span className="rail-bottom">SCROLL TO<br/>MAKE IT BRIGHT.</span></aside><div className="site-shell"><a className="skip-link" href="#intro">Vai al contenuto</a><Header/><main ref={root}><Hero/><section id="intro" className="intro section-pad"><div className="intro-line"/><LightReveal><h2>LA LUCE<br/>RENDE<br/>VISIBILI<br/><span className="yellow">LE IDEE.</span></h2></LightReveal><div className="intro-copy"><span className="small-spark" aria-hidden="true"/><p>Ci sono idee che aspettano solo di essere viste. Voci che meritano spazio. Una scuola che possiamo immaginare, insieme.</p><p>Per questo nasce <strong>Lumina.</strong><br/>Per accendere quello che siamo.</p></div></section><CandidateSection/><Countdown/><section className="manifesto section-pad" aria-label="Il nostro manifesto"><div className="manifesto-star" aria-hidden="true"/><h2><span className="manifesto-line">OGNI</span><span className="manifesto-line">IDEA</span><span className="manifesto-line">MERITA</span><span className="manifesto-line">DI ESSERE</span><span className="manifesto-line manifesto-outline">VISTA.</span></h2><p>LA NOSTRA DIREZIONE È INSIEME.</p></section><ProgramSection/><GadgetGallery/><div className="daybreak" aria-hidden="true"><span className="small-spark"/><span>ORA TOCCA A TE.</span></div><IdeaForm/></main><Footer/></div></>}
function Privacy(){return <div className="site-shell privacy-page section-pad"><Link to="/" className="text-link"><ArrowLeft size={18}/> TORNA A LUMINA</Link><h1>LA TUA IDEA.<br/>I TUOI DATI.</h1><p>Questa è una versione dimostrativa della landing Lumina — Lista 1.</p><h2>Raccolta delle idee</h2><p>La raccolta non è ancora attiva. Il modulo è predisposto per inviare l’idea, un identificativo dell’invio, la data e, solo se li inserisci, nome e classe a un Foglio Google gestito dalla lista.</p><h2>Prima dell’attivazione</h2><p>L’informativa definitiva dovrà indicare il responsabile della raccolta e i suoi contatti, le finalità, i tempi di conservazione, la base giuridica e come chiedere accesso o cancellazione. Queste informazioni non sono ancora state fornite.</p><h2>In questa anteprima</h2><p>Il testo digitato rimane nella memoria della pagina e non viene salvato in modo permanente sul dispositivo. Non sono presenti strumenti di analisi o cookie pubblicitari. Font e immagini sono ospitati insieme al sito.</p><Link className="text-link" to="/">TORNA ALLA LANDING <ArrowUpRight size={18}/></Link></div>}
function RouteReset(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0)},[pathname]);return null}
export default function App(){return <><RouteReset/><Routes><Route path="/" element={<Landing/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="*" element={<div className="site-shell privacy-page section-pad"><h1>QUI LA LUCE<br/>NON È ARRIVATA.</h1><p>Questa pagina non esiste.</p><Link className="text-link" to="/">TORNA A LUMINA <ArrowUpRight size={20}/></Link></div>}/></Routes></>}
